[package]
name="swikn"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true

[lib]
name = 'swikn'
path = 'src/lib.rs'

[dependencies]
serde_json = '^1'